configs:
  - id: statuscreated
    config:
      name: "EasyTrade \\[credit\\-card\\-order\\-service | Java\\] \\- POST /v1/orders/\\{id\\}/status:created"
      template: statuscreated.json
      skip: false
    type:
      settings:
        schema: builtin:bizevents.http.incoming
        scope: environment

  - id: statusdelivered
    config:
      name: "EasyTrade \\[credit\\-card\\-order\\-service | Java\\] \\- POST /v1/orders/\\{id\\}/status:delivered"
      template: statusdelivered.json
      skip: false
    type:
      settings:
        schema: builtin:bizevents.http.incoming
        scope: environment

  - id: statuserror
    config:
      name: "EasyTrade \\[credit\\-card\\-order\\-service | Java\\] \\- POST /v1/orders/\\{id\\}/status:error"
      template: statuserror.json
      skip: false
    type:
      settings:
        schema: builtin:bizevents.http.incoming
        scope: environment

  - id: statusshipped
    config:
      name: "EasyTrade \\[credit\\-card\\-order\\-service | Java\\] \\- POST /v1/orders/\\{id\\}/status:shipped"
      template: statusshipped.json
      skip: false
    type:
      settings:
        schema: builtin:bizevents.http.incoming
        scope: environment

  - id: v1Orders
    config:
      name: "EasyTrade \\[credit\\-card\\-order\\-service | Java\\] \\- POST /v1/orders"
      template: v1Orders.json
      skip: false
    type:
      settings:
        schema: builtin:bizevents.http.incoming
        scope: environment

  - id: SENSOR_DOTNET_BIZEVENTS_HTTP_INCOMING
    config:
      name: name
      template: SENSOR_DOTNET_BIZEVENTS_HTTP_INCOMING.json
      skip: false
    type:
      settings:
        schema: builtin:oneagent.features
        scope: environment

  - id: SENSOR_JAVA_BIZEVENTS_HTTP_INCOMING
    config:
      name: name
      template: SENSOR_JAVA_BIZEVENTS_HTTP_INCOMING.json
      skip: false
    type:
      settings:
        schema: builtin:oneagent.features
        scope: environment

 - id: openpipeline-revenue-addition
    type:
      openpipeline:
        kind: bizevents
    config:
      name: Revenue
      template: revenuePipeline.json
      skip: false
