
- name: Get k8s cluster UID
  shell: |
    kubectl get namespace kube-system --output jsonpath={.metadata.uid}
  register: k8s_cluster_uid

- name: Set variable for k8s cluster id
  set_fact:
    k8s_cluster_uid: "{{k8s_cluster_uid.stdout}}"

- name: Generate token workflow connection
  shell: |
    echo dt0e01.`openssl rand -out /dev/stdout 15 | base32 | tr '[:lower:]' '[:upper:]'`.`openssl rand -out /dev/stdout 40 | base32 | tr '[:lower:]' '[:upper:]'`
  register: edge_connect_token

- name: Generate variable for token
  set_fact:
    edge_connect_token: "{{edge_connect_token.stdout}}"