##
# Configure k8s workflow action connector setting
##
- name: Get k8s cluster UID
  shell: |
    kubectl get namespace kube-system --output jsonpath={.metadata.uid}
  register: k8s_cluster_uid

- name: Generate token workflow connection
  shell: |
    echo dt0e01.`openssl rand -out /dev/stdout 15 | base32 | tr '[:lower:]' '[:upper:]'`.`openssl rand -out /dev/stdout 40 | base32 | tr '[:lower:]' '[:upper:]'`
  register: token_workflow_config

# - name: Gitlab - Ensure Group
#   include_role:
#     name: gitlab
#     tasks_from: ensure-group
#   vars:
#     gitlab_group_name: "{{ gitlab_group }}"

- name: Gitlab - Additional Environment Variables
  include_role:
    name: gitlab
    tasks_from: ensure-group-var
  vars:
    gitlab_var_key: "{{ item.key }}"
    gitlab_var_value: "{{ item.value }}"
  loop:
    - {
        key: "K8S_TOKEN",
        value: "{{token_workflow_config.stdout}}",
      }
    - {
        key: "K8S_UID",
        value: "{{k8s_cluster_uid.stdout}}",
      }