# #
# https://dynatrace-docs-preview.spine-dev.internal.dynatracelabs.com/pr-1966/docs/platform-modules/automations/workflows/actions/kubernetes-automation/kubernetes-workflows-setup#define-service-account
# #

- name: edge connect service account
  kubernetes.core.k8s:
    state: present
    src: "{{ role_path }}/templates/edgeconnect-serviceaccount.yaml"

- name: edge connect role
  kubernetes.core.k8s:
    state: present
    src: "{{ role_path }}/templates/edgeconnect-role.yaml"

- name: edge connect role binding
  kubernetes.core.k8s:
    state: present
    src: "{{ role_path }}/templates/edgeconnect-rolebinding.yaml"

##
# https://dynatrace-docs-preview.spine-dev.internal.dynatracelabs.com/pr-1966/docs/setup-and-configuration/setup-on-k8s/guides/operation/edgeconnect/edge-connect-provision#create-oauth-client
##

- set_fact:
    dt_tenant_gen3_no_protocol: "{{ extra_vars.dt_environment_url_gen3 | regex_search('[^\/\/]*$') }}"

- name: Template secret for edge connect
  ansible.builtin.template:
    src: "edgeconnect-oauth-secret.yaml.j2"
    dest: "{{ role_path }}/templates/edgeconnect-oauth-secret.yaml"
    owner: "{{ ace_box_user }}"
    group: "{{ ace_box_user }}"
    mode: "0644"

- name: Apply secret for edge connect
  kubernetes.core.k8s:
    state: present
    src: "{{ role_path }}/templates/edgeconnect-oauth-secret.yaml"
  delay: 5

- set_fact:
    tenant_id: "{{ dt_tenant_gen3_no_protocol | split('.') }}"

- name: Print response
  debug: "msg='{{ tenant_id[0] }}'"

- name: Template edge connect
  ansible.builtin.template:
    src: "edgeconnect.yaml.j2"
    dest: "{{ role_path }}/templates/edgeconnect.yaml"
    owner: "{{ ace_box_user }}"
    group: "{{ ace_box_user }}"
    mode: "0644"
    
- name: Apply edge connect
  kubernetes.core.k8s:
    state: present
    src: "{{ role_path }}/templates/edgeconnect.yaml"
  delay: 5

- name: Request a DT OAuth access token
  ansible.builtin.uri:
    url: "{{ extra_vars.dt_oauth_sso_endpoint }}"
    method: POST
    status_code: 200
    headers:
      Content-Type: "application/x-www-form-urlencoded"
    body_format: form-urlencoded
    body:
      grant_type: "client_credentials"
      client_id: "{{ extra_vars.dt_oauth_client_id }}"
      client_secret: "{{ extra_vars.dt_oauth_client_secret }}"
      scope: "app-engine:apps:install"
      resource: "{{ extra_vars.dt_oauth_account_urn }}"
  register: auth_response_raw
- set_fact:
    dt_oauth_access_token: "{{ auth_response_raw.json.access_token }}"