apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: edgeconnect-deployment-rollout-restart
  namespace: default
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "patch"]